"""authmap.generator — Generate reusable Python auth modules from detected flows."""

from __future__ import annotations

import textwrap
from typing import List

from rekit.authmap.detector import AuthFlow, AuthFlowType


def generate_auth_module(flows: List[AuthFlow], class_name: str = "ApiAuth") -> str:
    """Generate a Python auth module from detected authentication flows.

    Produces a standalone Python file with a class that handles authentication,
    including token refresh, session management, and request preparation.

    Args:
        flows: List of detected AuthFlow objects.
        class_name: Name for the generated auth class.

    Returns:
        Complete Python source code as a string.
    """
    parts: List[str] = []

    # Module header
    parts.append(
        textwrap.dedent('''\
        """Auto-generated authentication module.

        Generated by rekit authmap from captured HTTP traffic.
        """

        import time
        from typing import Dict, Optional, Tuple

        import requests
        ''')
    )

    for flow in flows:
        if flow.flow_type in (
            AuthFlowType.OAUTH2_AUTH_CODE,
            AuthFlowType.OAUTH2_PKCE,
        ):
            parts.append(_generate_oauth2_auth_code_class(flow, class_name))
        elif flow.flow_type == AuthFlowType.OAUTH2_CLIENT_CREDENTIALS:
            parts.append(_generate_oauth2_client_credentials_class(flow, class_name))
        elif flow.flow_type == AuthFlowType.CUSTOM_LOGIN:
            parts.append(_generate_custom_login_class(flow, class_name))
        elif flow.flow_type == AuthFlowType.API_KEY_STATIC:
            parts.append(_generate_api_key_class(flow, class_name))
        elif flow.flow_type == AuthFlowType.SESSION_COOKIE:
            parts.append(_generate_session_cookie_class(flow, class_name))
        elif flow.flow_type == AuthFlowType.BASIC_AUTH:
            parts.append(_generate_basic_auth_class(flow, class_name))
        elif flow.flow_type == AuthFlowType.BEARER_TOKEN:
            parts.append(_generate_bearer_token_class(flow, class_name))
        elif flow.flow_type == AuthFlowType.HMAC_SIGNATURE:
            parts.append(_generate_hmac_class(flow, class_name))

    if not parts[1:]:
        # No specific flows, generate a stub
        parts.append(_generate_stub_class(class_name))

    return "\n".join(parts)


def _generate_oauth2_auth_code_class(flow: AuthFlow, class_name: str) -> str:
    """Generate OAuth2 authorization code / PKCE auth class."""
    token_endpoint = flow.token_endpoint or "https://example.com/oauth/token"
    redirect_uri = flow.redirect_uri or "https://example.com/callback"
    pkce_note = ""
    if flow.flow_type == AuthFlowType.OAUTH2_PKCE:
        pkce_note = (
            "\n    # PKCE flow detected — include code_verifier in token exchange"
        )

    return textwrap.dedent(f'''\

    class {class_name}:
        """OAuth2 Authorization Code authentication handler."""
        {pkce_note}
        TOKEN_ENDPOINT = "{token_endpoint}"
        REDIRECT_URI = "{redirect_uri}"

        def __init__(
            self,
            client_id: str,
            client_secret: Optional[str] = None,
        ):
            self.client_id = client_id
            self.client_secret = client_secret
            self.session = requests.Session()
            self._access_token: Optional[str] = None
            self._refresh_token: Optional[str] = None
            self._expires_at: float = 0.0

        def login(self, authorization_code: str, code_verifier: Optional[str] = None) -> dict:
            """Exchange authorization code for tokens."""
            data = {{
                "grant_type": "authorization_code",
                "code": authorization_code,
                "redirect_uri": self.REDIRECT_URI,
                "client_id": self.client_id,
            }}
            if self.client_secret:
                data["client_secret"] = self.client_secret
            if code_verifier:
                data["code_verifier"] = code_verifier
            resp = self.session.post(self.TOKEN_ENDPOINT, data=data)
            resp.raise_for_status()
            tokens = resp.json()
            self._access_token = tokens.get("access_token")
            self._refresh_token = tokens.get("refresh_token")
            expires_in = tokens.get("expires_in", 3600)
            self._expires_at = time.time() + int(expires_in)
            return tokens

        def refresh_token(self) -> dict:
            """Refresh the access token using the refresh token."""
            if not self._refresh_token:
                raise ValueError("No refresh token available")
            data = {{
                "grant_type": "refresh_token",
                "refresh_token": self._refresh_token,
                "client_id": self.client_id,
            }}
            if self.client_secret:
                data["client_secret"] = self.client_secret
            resp = self.session.post(self.TOKEN_ENDPOINT, data=data)
            resp.raise_for_status()
            tokens = resp.json()
            self._access_token = tokens.get("access_token")
            if "refresh_token" in tokens:
                self._refresh_token = tokens["refresh_token"]
            expires_in = tokens.get("expires_in", 3600)
            self._expires_at = time.time() + int(expires_in)
            return tokens

        def _ensure_token(self) -> str:
            """Ensure a valid access token is available, refreshing if needed."""
            if self._access_token and time.time() < self._expires_at - 30:
                return self._access_token
            if self._refresh_token:
                self.refresh_token()
                return self._access_token  # type: ignore[return-value]
            raise ValueError("No valid token available. Call login() first.")

        def prepare_request(
            self, method: str, url: str, headers: Optional[Dict[str, str]] = None
        ) -> Tuple[str, str, Dict[str, str]]:
            """Add authentication to a request."""
            headers = dict(headers) if headers else {{}}
            token = self._ensure_token()
            headers["Authorization"] = f"Bearer {{token}}"
            return method, url, headers
    ''')


def _generate_oauth2_client_credentials_class(flow: AuthFlow, class_name: str) -> str:
    """Generate OAuth2 client credentials auth class."""
    token_endpoint = flow.token_endpoint or "https://example.com/oauth/token"

    return textwrap.dedent(f'''\

    class {class_name}:
        """OAuth2 Client Credentials authentication handler."""

        TOKEN_ENDPOINT = "{token_endpoint}"

        def __init__(self, client_id: str, client_secret: str):
            self.client_id = client_id
            self.client_secret = client_secret
            self.session = requests.Session()
            self._access_token: Optional[str] = None
            self._expires_at: float = 0.0

        def login(self) -> dict:
            """Obtain access token using client credentials."""
            data = {{
                "grant_type": "client_credentials",
                "client_id": self.client_id,
                "client_secret": self.client_secret,
            }}
            resp = self.session.post(self.TOKEN_ENDPOINT, data=data)
            resp.raise_for_status()
            tokens = resp.json()
            self._access_token = tokens.get("access_token")
            expires_in = tokens.get("expires_in", 3600)
            self._expires_at = time.time() + int(expires_in)
            return tokens

        def refresh_token(self) -> dict:
            """Re-obtain token (client credentials do not use refresh tokens)."""
            return self.login()

        def _ensure_token(self) -> str:
            """Ensure a valid access token is available."""
            if self._access_token and time.time() < self._expires_at - 30:
                return self._access_token
            self.login()
            return self._access_token  # type: ignore[return-value]

        def prepare_request(
            self, method: str, url: str, headers: Optional[Dict[str, str]] = None
        ) -> Tuple[str, str, Dict[str, str]]:
            """Add authentication to a request."""
            headers = dict(headers) if headers else {{}}
            token = self._ensure_token()
            headers["Authorization"] = f"Bearer {{token}}"
            return method, url, headers
    ''')


def _generate_custom_login_class(flow: AuthFlow, class_name: str) -> str:
    """Generate custom login auth class."""
    login_endpoint = flow.login_endpoint or "https://example.com/login"

    return textwrap.dedent(f'''\

    class {class_name}:
        """Custom login authentication handler."""

        LOGIN_ENDPOINT = "{login_endpoint}"

        def __init__(self, username: str, password: str):
            self.username = username
            self.password = password
            self.session = requests.Session()
            self._access_token: Optional[str] = None
            self._expires_at: float = 0.0

        def authenticate(self) -> dict:
            """Authenticate via login endpoint."""
            data = {{
                "username": self.username,
                "password": self.password,
            }}
            resp = self.session.post(self.LOGIN_ENDPOINT, json=data)
            resp.raise_for_status()
            result = resp.json()
            self._access_token = result.get("access_token") or result.get("token")
            expires_in = result.get("expires_in", 3600)
            self._expires_at = time.time() + int(expires_in)
            return result

        def _ensure_token(self) -> str:
            """Ensure a valid token is available."""
            if self._access_token and time.time() < self._expires_at - 30:
                return self._access_token
            self.authenticate()
            return self._access_token  # type: ignore[return-value]

        def prepare_request(
            self, method: str, url: str, headers: Optional[Dict[str, str]] = None
        ) -> Tuple[str, str, Dict[str, str]]:
            """Add authentication to a request."""
            headers = dict(headers) if headers else {{}}
            token = self._ensure_token()
            headers["Authorization"] = f"Bearer {{token}}"
            return method, url, headers
    ''')


def _generate_api_key_class(flow: AuthFlow, class_name: str) -> str:
    """Generate API key auth class."""
    header_name = "X-API-Key"
    if flow.tokens_involved:
        header_name = next(iter(flow.tokens_involved))

    return textwrap.dedent(f'''\

    class {class_name}:
        """API Key authentication handler."""

        HEADER_NAME = "{header_name}"

        def __init__(self, api_key: str):
            self.api_key = api_key
            self.session = requests.Session()

        def prepare_request(
            self, method: str, url: str, headers: Optional[Dict[str, str]] = None
        ) -> Tuple[str, str, Dict[str, str]]:
            """Add API key header to a request."""
            headers = dict(headers) if headers else {{}}
            headers[self.HEADER_NAME] = self.api_key
            return method, url, headers
    ''')


def _generate_session_cookie_class(flow: AuthFlow, class_name: str) -> str:
    """Generate session cookie auth class."""
    login_endpoint = flow.login_endpoint or "https://example.com/login"

    return textwrap.dedent(f'''\

    class {class_name}:
        """Session cookie authentication handler."""

        LOGIN_ENDPOINT = "{login_endpoint}"

        def __init__(self, username: str, password: str):
            self.username = username
            self.password = password
            self.session = requests.Session()

        def authenticate(self) -> requests.Response:
            """Authenticate and store session cookies."""
            data = {{
                "username": self.username,
                "password": self.password,
            }}
            resp = self.session.post(self.LOGIN_ENDPOINT, data=data)
            resp.raise_for_status()
            return resp

        def prepare_request(
            self, method: str, url: str, headers: Optional[Dict[str, str]] = None
        ) -> Tuple[str, str, Dict[str, str]]:
            """Prepare request with session cookies (handled by self.session)."""
            headers = dict(headers) if headers else {{}}
            return method, url, headers
    ''')


def _generate_basic_auth_class(flow: AuthFlow, class_name: str) -> str:
    """Generate HTTP Basic auth class."""
    return textwrap.dedent(f'''\

    class {class_name}:
        """HTTP Basic authentication handler."""

        def __init__(self, username: str, password: str):
            self.username = username
            self.password = password
            self.session = requests.Session()
            self.session.auth = (self.username, self.password)

        def prepare_request(
            self, method: str, url: str, headers: Optional[Dict[str, str]] = None
        ) -> Tuple[str, str, Dict[str, str]]:
            """Add Basic auth to a request."""
            import base64

            headers = dict(headers) if headers else {{}}
            credentials = base64.b64encode(
                f"{{self.username}}:{{self.password}}".encode()
            ).decode()
            headers["Authorization"] = f"Basic {{credentials}}"
            return method, url, headers
    ''')


def _generate_bearer_token_class(flow: AuthFlow, class_name: str) -> str:
    """Generate static bearer token auth class."""
    return textwrap.dedent(f'''\

    class {class_name}:
        """Static Bearer token authentication handler."""

        def __init__(self, token: str):
            self.token = token
            self.session = requests.Session()

        def prepare_request(
            self, method: str, url: str, headers: Optional[Dict[str, str]] = None
        ) -> Tuple[str, str, Dict[str, str]]:
            """Add Bearer token to a request."""
            headers = dict(headers) if headers else {{}}
            headers["Authorization"] = f"Bearer {{self.token}}"
            return method, url, headers
    ''')


def _generate_hmac_class(flow: AuthFlow, class_name: str) -> str:
    """Generate HMAC signature auth class."""
    sig_header = "X-Signature"
    if flow.tokens_involved:
        sig_header = next(iter(flow.tokens_involved))

    return textwrap.dedent(f'''\

    class {class_name}:
        """HMAC Signature authentication handler."""

        SIGNATURE_HEADER = "{sig_header}"

        def __init__(self, api_key: str, secret_key: str):
            self.api_key = api_key
            self.secret_key = secret_key
            self.session = requests.Session()

        def _sign_request(self, method: str, url: str, body: str = "") -> str:
            """Generate HMAC signature for a request."""
            import hashlib
            import hmac as hmac_mod

            timestamp = str(int(time.time()))
            message = f"{{method}}\\n{{url}}\\n{{timestamp}}\\n{{body}}"
            signature = hmac_mod.new(
                self.secret_key.encode(),
                message.encode(),
                hashlib.sha256,
            ).hexdigest()
            return signature

        def prepare_request(
            self, method: str, url: str, headers: Optional[Dict[str, str]] = None
        ) -> Tuple[str, str, Dict[str, str]]:
            """Add HMAC signature to a request."""
            import time as time_mod

            headers = dict(headers) if headers else {{}}
            signature = self._sign_request(method, url)
            headers[self.SIGNATURE_HEADER] = signature
            headers["X-Timestamp"] = str(int(time_mod.time()))
            return method, url, headers
    ''')


def _generate_stub_class(class_name: str) -> str:
    """Generate a stub auth class when no specific flow is detected."""
    return textwrap.dedent(f'''\

    class {class_name}:
        """Authentication handler (no specific flow detected)."""

        def __init__(self):
            self.session = requests.Session()

        def prepare_request(
            self, method: str, url: str, headers: Optional[Dict[str, str]] = None
        ) -> Tuple[str, str, Dict[str, str]]:
            """Prepare a request (no auth added)."""
            headers = dict(headers) if headers else {{}}
            return method, url, headers
    ''')
