"""
hargen.generator — Generate typed Python API client code from an ApiSpec.

Produces two files:
  - models.py: Dataclass models for request/response bodies
  - client.py: Client class with typed methods for each endpoint

Uses Jinja2 templates (inline) for clean, maintainable output.
"""

from __future__ import annotations

import keyword
import logging
import re
import textwrap
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional, Set, Tuple

from jinja2 import Environment, BaseLoader
from rich.console import Console

from rekit.hargen.analyzer import ApiSpec, FieldSchema

logger = logging.getLogger(__name__)
console = Console(stderr=True)

# ---------------------------------------------------------------------------
# Jinja2 templates
# ---------------------------------------------------------------------------

MODELS_TEMPLATE = textwrap.dedent('''\
    """
    Auto-generated API models for {{ client_name }}.

    Generated by rekit hargen from captured HTTP traffic.
    Do not edit directly — regenerate from updated traffic captures.
    """

    from __future__ import annotations

    from dataclasses import dataclass, field
    from typing import Any, Dict, List, Optional


    {% for model in models %}
    @dataclass
    class {{ model.class_name }}:
        """{{ model.docstring }}"""
    {% for f in model.fields %}
        {{ f.attr_name }}: {{ f.type_annotation }}{{ f.default }}
    {% endfor %}
    {% if not model.fields %}
        pass
    {% endif %}

        @classmethod
        def from_dict(cls, data: Dict[str, Any]) -> "{{ model.class_name }}":
            """Create an instance from a dictionary."""
            if data is None:
                data = {}
            return cls(
    {% for f in model.fields %}
    {% if f.nested_model %}
                {{ f.attr_name }}={{ f.nested_from_dict }},
    {% else %}
                {{ f.attr_name }}=data.get({{ f.key_repr }}, {{ f.default_value_repr }}),
    {% endif %}
    {% endfor %}
            )

        def to_dict(self) -> Dict[str, Any]:
            """Convert to a dictionary for serialization."""
            result: Dict[str, Any] = {}
    {% for f in model.fields %}
    {% if f.nested_model %}
    {% if f.is_list %}
            result[{{ f.key_repr }}] = [item.to_dict() for item in self.{{ f.attr_name }}] if self.{{ f.attr_name }} else []
    {% else %}
            result[{{ f.key_repr }}] = self.{{ f.attr_name }}.to_dict() if self.{{ f.attr_name }} else None
    {% endif %}
    {% else %}
            result[{{ f.key_repr }}] = self.{{ f.attr_name }}
    {% endif %}
    {% endfor %}
            return result

    {% endfor %}
''')

CLIENT_TEMPLATE = textwrap.dedent('''\
    """
    Auto-generated API client for {{ client_name }}.

    Generated by rekit hargen from captured HTTP traffic.
    Do not edit directly — regenerate from updated traffic captures.

    Usage:
        from {{ package_name }}.client import {{ client_name }}

        client = {{ client_name }}(
            base_url="{{ base_url }}",
    {% for h in auth_headers %}
            # {{ h.name }}: {{ h.example_value }}
    {% endfor %}
        )
    """

    from __future__ import annotations

    from typing import Any, Dict, List, Optional

    import requests

    from {{ package_name }}.models import (
    {% for model_name in model_imports %}
        {{ model_name }},
    {% endfor %}
    )


    class {{ client_name }}:
        """
        API client for {{ base_url }}.

        Provides typed methods for each discovered endpoint.
        """

        def __init__(
            self,
            base_url: str = "{{ base_url }}",
            headers: Optional[Dict[str, str]] = None,
            timeout: float = 30.0,
        ) -> None:
            self.base_url = base_url.rstrip("/")
            self.timeout = timeout
            self.session = requests.Session()

            # Static headers (observed in all requests)
    {% for h in static_headers %}
            self.session.headers["{{ h.name }}"] = "{{ h.example_value }}"
    {% endfor %}

    {% for h in auth_headers %}
            # TODO: Set authentication header '{{ h.name }}' (pattern: {{ h.example_value }})
            # self.session.headers["{{ h.name }}"] = "<your-{{ h.name }}>"
    {% endfor %}

    {% for h in dynamic_headers %}
            # NOTE: Dynamic header '{{ h.name }}' changes per-request (trace ID, timestamp, etc.)
    {% endfor %}

            # Override with user-provided headers
            if headers:
                self.session.headers.update(headers)

        def close(self) -> None:
            """Close the underlying HTTP session."""
            self.session.close()

        def __enter__(self) -> "{{ client_name }}":
            return self

        def __exit__(self, *args: Any) -> None:
            self.close()

    {% for ep in endpoints %}
        def {{ ep.func_name }}(
            self,
    {% for p in ep.path_params %}
            {{ p.name }}: {{ p.type_str }},
    {% endfor %}
    {% if ep.request_model %}
            body: {{ ep.request_model }},
    {% endif %}
    {% for qp in ep.required_query_params %}
            {{ qp.name }}: {{ qp.type_str }},
    {% endfor %}
    {% for qp in ep.optional_query_params %}
            {{ qp.name }}: Optional[{{ qp.type_str }}] = None,
    {% endfor %}
        ) -> {{ ep.return_type }}:
            """
            {{ ep.method }} {{ ep.path_pattern }}

            {% if ep.status_codes %}Observed status codes: {{ ep.status_codes | join(", ") }}{% endif %}

            {% if ep.request_count > 1 %}Seen {{ ep.request_count }} times in traffic.{% endif %}
            """
    {% if ep.path_params %}
            url = f"{self.base_url}{{ ep.path_format_str }}"
    {% else %}
            url = f"{self.base_url}{{ ep.path_pattern }}"
    {% endif %}

            params: Dict[str, Any] = {}
    {% for qp in ep.all_query_params %}
    {% if qp.required %}
            params["{{ qp.original_name }}"] = {{ qp.name }}
    {% else %}
            if {{ qp.name }} is not None:
                params["{{ qp.original_name }}"] = {{ qp.name }}
    {% endif %}
    {% endfor %}

    {% if ep.method == "GET" %}
            resp = self.session.get(url, params=params, timeout=self.timeout)
    {% elif ep.method == "DELETE" %}
            resp = self.session.delete(url, params=params, timeout=self.timeout)
    {% elif ep.method == "POST" %}
            resp = self.session.post(
                url, params=params, json=body.to_dict() if body else None, timeout=self.timeout
            )
    {% elif ep.method == "PUT" %}
            resp = self.session.put(
                url, params=params, json=body.to_dict() if body else None, timeout=self.timeout
            )
    {% elif ep.method == "PATCH" %}
            resp = self.session.patch(
                url, params=params, json=body.to_dict() if body else None, timeout=self.timeout
            )
    {% else %}
            resp = self.session.request(
                "{{ ep.method }}", url, params=params, timeout=self.timeout
            )
    {% endif %}
            resp.raise_for_status()

    {% if ep.returns_model %}
    {% if ep.returns_list %}
            data = resp.json()
            return [{{ ep.item_model }}.from_dict(item) for item in data]
    {% else %}
            return {{ ep.response_model }}.from_dict(resp.json())
    {% endif %}
    {% else %}
            return resp.json() if resp.content else None
    {% endif %}

    {% endfor %}
''')


# ---------------------------------------------------------------------------
# Template context builders
# ---------------------------------------------------------------------------


@dataclass
class _ModelField:
    """Template context for a single model field."""

    attr_name: str
    key_repr: str  # repr of the original dict key
    type_annotation: str
    default: str  # e.g., " = None" or " = field(default_factory=list)"
    default_value_repr: str  # Python repr for from_dict default
    nested_model: str  # Empty string if not nested
    nested_from_dict: str  # Expression for from_dict with nested model
    is_list: bool
    example: Any


@dataclass
class _ModelDef:
    """Template context for a model class."""

    class_name: str
    docstring: str
    fields: List[_ModelField]


@dataclass
class _EndpointDef:
    """Template context for a client method."""

    func_name: str
    method: str
    path_pattern: str
    path_format_str: str  # Python f-string path e.g., /api/listings/{listing_id}
    path_params: List[Dict[str, str]]
    request_model: str
    response_model: str
    item_model: str  # For list responses
    return_type: str
    returns_model: bool
    returns_list: bool
    required_query_params: List[Dict[str, str]]
    optional_query_params: List[Dict[str, str]]
    all_query_params: List[Dict[str, Any]]
    status_codes: List[int]
    request_count: int


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def generate_client(
    spec: ApiSpec,
    output_dir: str | Path,
    client_name: str = "ApiClient",
    package_name: str = "api_client",
) -> Path:
    """
    Generate a typed Python API client from an ApiSpec.

    Creates an output directory with:
      - __init__.py (package marker)
      - models.py (dataclass models)
      - client.py (client class)

    Args:
        spec: The analyzed API specification.
        output_dir: Directory to write generated files into.
        client_name: Name for the client class (e.g., "IdealIstaClient").
        package_name: Python package name for imports within generated code.

    Returns:
        Path to the output directory.
    """
    output = Path(output_dir)
    output.mkdir(parents=True, exist_ok=True)

    # Collect all models needed
    models, model_names_set = _collect_models(spec, client_name)

    # Build endpoint definitions
    endpoints = _build_endpoint_defs(spec, model_names_set)

    # Classify headers
    static_headers = [h for h in spec.common_headers if h.classification == "static"]
    dynamic_headers = [h for h in spec.common_headers if h.classification == "dynamic"]
    auth_headers = spec.auth_headers

    # All model names for imports in client.py
    model_imports = sorted(m.class_name for m in models)

    # Render templates
    env = Environment(
        loader=BaseLoader(),
        keep_trailing_newline=True,
        trim_blocks=True,
        lstrip_blocks=True,
    )
    env.globals["repr"] = repr

    models_code = env.from_string(MODELS_TEMPLATE).render(
        client_name=client_name,
        models=models,
    )

    client_code = env.from_string(CLIENT_TEMPLATE).render(
        client_name=client_name,
        package_name=package_name,
        base_url=spec.base_url,
        static_headers=static_headers,
        dynamic_headers=dynamic_headers,
        auth_headers=auth_headers,
        model_imports=model_imports,
        endpoints=endpoints,
    )

    # Write files
    init_path = output / "__init__.py"
    models_path = output / "models.py"
    client_path = output / "client.py"

    init_path.write_text(
        f'"""\nAuto-generated API client package: {package_name}\n"""\n',
        encoding="utf-8",
    )
    models_path.write_text(models_code, encoding="utf-8")
    client_path.write_text(client_code, encoding="utf-8")

    console.print(f"[green]Generated client:[/green] {output}")
    console.print(f"  [dim]{init_path}[/dim]")
    console.print(f"  [dim]{models_path}[/dim]")
    console.print(f"  [dim]{client_path}[/dim]")
    console.print(f"  [dim]{len(models)} models, {len(endpoints)} endpoints[/dim]")

    return output


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _sanitize_name(name: str) -> str:
    """Sanitize a string to be a valid Python identifier."""
    # Replace non-alphanumeric chars with underscores
    clean = re.sub(r"[^a-zA-Z0-9_]", "_", name)
    # Remove leading digits
    clean = re.sub(r"^(\d)", r"_\1", clean)
    # Deduplicate underscores
    clean = re.sub(r"_+", "_", clean).strip("_")
    # Avoid Python keywords
    if keyword.iskeyword(clean):
        clean = clean + "_"
    return clean or "field_"


def _to_class_name(name: str) -> str:
    """Convert a string to PascalCase class name."""
    parts = re.split(r"[_\-\s]+", name)
    return "".join(p.capitalize() for p in parts if p)


def _collect_models(
    spec: ApiSpec, client_name: str
) -> Tuple[List[_ModelDef], Set[str]]:
    """
    Collect all model definitions needed from the ApiSpec.

    Returns (list of _ModelDef, set of model class names).
    """
    models: List[_ModelDef] = []
    names_used: Set[str] = set()

    def _unique_name(base: str) -> str:
        name = base
        counter = 2
        while name in names_used:
            name = f"{base}{counter}"
            counter += 1
        names_used.add(name)
        return name

    def _schema_to_model(
        schema: List[FieldSchema],
        class_name: str,
        docstring: str,
    ) -> Optional[_ModelDef]:
        """Recursively convert a FieldSchema list to a _ModelDef."""
        if not schema:
            return None

        # Skip pseudo-schemas (single _items or _value)
        if len(schema) == 1 and schema[0].name in ("_items", "_value"):
            # For list responses, we process the nested items
            fs = schema[0]
            if fs.nested:
                return _schema_to_model(fs.nested, class_name, docstring)
            return None

        fields: List[_ModelField] = []
        for fs in schema:
            if fs.name.startswith("_"):
                continue

            attr_name = _sanitize_name(fs.name)
            key_repr = repr(fs.name)

            nested_model = ""
            nested_from_dict = ""
            is_list = False

            # Check for nested object fields
            if fs.nested and fs.type_str.startswith("List["):
                # List of nested objects
                inner_name = _unique_name(_to_class_name(fs.name) + "Item")
                inner_model = _schema_to_model(
                    fs.nested, inner_name, f"Item in {fs.name}"
                )
                if inner_model:
                    models.append(inner_model)
                    nested_model = inner_name
                    is_list = True
                    type_annotation = f"List[{inner_name}]"
                    nested_from_dict = f"[{inner_name}.from_dict(item) for item in data.get({key_repr}, [])]"
                else:
                    type_annotation = _clean_type(fs.type_str, fs.optional)
            elif fs.nested and (
                "Dict[" in fs.type_str or "Optional[Dict[" in fs.type_str
            ):
                # Nested object
                inner_name = _unique_name(_to_class_name(fs.name))
                inner_model = _schema_to_model(
                    fs.nested, inner_name, f"Schema for {fs.name}"
                )
                if inner_model:
                    models.append(inner_model)
                    nested_model = inner_name
                    if fs.optional:
                        type_annotation = f"Optional[{inner_name}]"
                        nested_from_dict = (
                            f"{inner_name}.from_dict(data[{key_repr}]) "
                            f"if {key_repr} in data and data[{key_repr}] is not None "
                            f"else None"
                        )
                    else:
                        type_annotation = inner_name
                        nested_from_dict = (
                            f"{inner_name}.from_dict(data.get({key_repr}, {{}}))"
                        )
                else:
                    type_annotation = _clean_type(fs.type_str, fs.optional)
            else:
                type_annotation = _clean_type(fs.type_str, fs.optional)

            # Determine default value
            if fs.optional:
                default = " = None"
                default_value_repr = "None"
            elif "List[" in type_annotation and not nested_model:
                default = " = field(default_factory=list)"
                default_value_repr = "[]"
            else:
                default = ""
                default_value_repr = "None"

            fields.append(
                _ModelField(
                    attr_name=attr_name,
                    key_repr=key_repr,
                    type_annotation=type_annotation,
                    default=default,
                    default_value_repr=default_value_repr,
                    nested_model=nested_model,
                    nested_from_dict=nested_from_dict,
                    is_list=is_list,
                    example=fs.example_value,
                )
            )

        # Sort: required fields first (those without defaults), then optional
        fields.sort(key=lambda f: (bool(f.default), f.attr_name))

        return _ModelDef(
            class_name=class_name,
            docstring=docstring,
            fields=fields,
        )

    # Process each endpoint
    for ep in spec.endpoints:
        # Response model
        if ep.response_schema:
            resp_name = _unique_name(ep.response_model_name)
            resp_model = _schema_to_model(
                ep.response_schema,
                resp_name,
                f"Response model for {ep.method} {ep.path_pattern}",
            )
            if resp_model:
                models.append(resp_model)

        # Request model
        if ep.request_schema:
            req_name = _unique_name(ep.request_model_name)
            req_model = _schema_to_model(
                ep.request_schema,
                req_name,
                f"Request model for {ep.method} {ep.path_pattern}",
            )
            if req_model:
                models.append(req_model)

    return models, names_used


def _clean_type(type_str: str, optional: bool = False) -> str:
    """Clean up a type string for use in generated code."""
    # Ensure Optional wrapping is correct
    if optional and not type_str.startswith("Optional["):
        return f"Optional[{type_str}]"
    return type_str


def _build_endpoint_defs(spec: ApiSpec, model_names: Set[str]) -> List[_EndpointDef]:
    """Build template context for each endpoint method."""
    endpoints: List[_EndpointDef] = []
    func_names_used: Set[str] = set()

    for ep in spec.endpoints:
        func_name = ep.function_name
        # Ensure unique function names
        counter = 2
        base_name = func_name
        while func_name in func_names_used:
            func_name = f"{base_name}_{counter}"
            counter += 1
        func_names_used.add(func_name)

        # Path params
        path_params = [
            {"name": _sanitize_name(p.name), "type_str": p.type_str}
            for p in ep.path_params
        ]

        # Build f-string for path with params
        path_format = ep.path_pattern
        for p in ep.path_params:
            safe_name = _sanitize_name(p.name)
            path_format = path_format.replace(f"{{{p.name}}}", f"{{{safe_name}}}")

        # Request model
        request_model = ""
        if ep.request_schema and ep.method in ("POST", "PUT", "PATCH"):
            candidate = ep.request_model_name
            if candidate in model_names:
                request_model = candidate

        # Response model
        response_model = ""
        item_model = ""
        returns_model = False
        returns_list = False
        return_type = "Any"

        if ep.response_schema:
            candidate = ep.response_model_name
            if candidate in model_names:
                # Check if response is a list
                if (
                    len(ep.response_schema) == 1
                    and ep.response_schema[0].name == "_items"
                    and ep.response_schema[0].nested
                ):
                    # List response
                    item_name = _to_class_name(ep.response_schema[0].name) + "Item"
                    # Find the actual model name (may have been renamed)
                    for mn in model_names:
                        if mn.startswith(item_name) or mn == candidate:
                            item_model = mn
                            break
                    if item_model:
                        returns_list = True
                        returns_model = True
                        return_type = f"List[{item_model}]"
                    else:
                        response_model = candidate
                        returns_model = True
                        return_type = candidate
                else:
                    response_model = candidate
                    returns_model = True
                    return_type = candidate
            else:
                return_type = "Any"

        # Query params
        required_qp = []
        optional_qp = []
        all_qp = []
        for qp in ep.query_params:
            safe_name = _sanitize_name(qp.name)
            entry = {
                "name": safe_name,
                "original_name": qp.name,
                "type_str": qp.type_str,
                "required": qp.required,
            }
            all_qp.append(entry)
            if qp.required:
                required_qp.append(entry)
            else:
                optional_qp.append(entry)

        endpoints.append(
            _EndpointDef(
                func_name=func_name,
                method=ep.method,
                path_pattern=ep.path_pattern,
                path_format_str=path_format,
                path_params=path_params,
                request_model=request_model,
                response_model=response_model,
                item_model=item_model,
                return_type=return_type,
                returns_model=returns_model,
                returns_list=returns_list,
                required_query_params=required_qp,
                optional_query_params=optional_qp,
                all_query_params=all_qp,
                status_codes=ep.status_codes,
                request_count=ep.request_count,
            )
        )

    return endpoints
